'use client'
import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function CreatePostForm(){
 const supabase=createClient(); const router=useRouter(); const uploadRef=useRef<HTMLInputElement>(null); const cameraRef=useRef<HTMLInputElement>(null); const liveVideoRef=useRef<HTMLVideoElement>(null); const liveStreamRef=useRef<MediaStream|null>(null); const cancelRef=useRef(false)
 const [file,setFile]=useState<File|null>(null); const [live,setLive]=useState(false); const [liveError,setLiveError]=useState(''); const [liveBusy,setLiveBusy]=useState(false); const [caption,setCaption]=useState(''); const [visibility,setVisibility]=useState('public'); const [busy,setBusy]=useState(false); const [cancelled,setCancelled]=useState(false); const [preview,setPreview]=useState<string|null>(null)
 useEffect(()=>()=>{liveStreamRef.current?.getTracks().forEach(t=>t.stop())},[])
 function choose(f:File|undefined){if(!f)return;if(!['image/','video/'].some(p=>f.type.startsWith(p)))return alert('Choose an image or video.');if(f.size>50*1024*1024)return alert('Maximum file size is 50 MB.');cancelRef.current=false;setCancelled(false);setFile(f);setPreview(URL.createObjectURL(f))}
 async function openLive(){setLive(true);setLiveError('');setLiveBusy(true);try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('This browser does not provide camera access.');const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});liveStreamRef.current=stream;if(liveVideoRef.current){liveVideoRef.current.srcObject=stream;await liveVideoRef.current.play().catch(()=>{})}const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.from('live_streams').insert({host_user_id:user.id,title:'Mirror Gram Live',category:'creator',status:'live',started_at:new Date().toISOString()})}catch(e){setLiveError(e instanceof Error?e.message:'Camera access was denied. Check your browser camera/microphone permission.')}finally{setLiveBusy(false)}}
 function closeLive(){liveStreamRef.current?.getTracks().forEach(t=>t.stop());liveStreamRef.current=null;setLive(false)}
 function cancelUpload(){if(!busy)return;cancelRef.current=true;setCancelled(true);setBusy(false)}
 async function publish(){if(!file)return alert('Choose a photo or video first.');if(busy)return;cancelRef.current=false;setCancelled(false);setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return router.push('/login')}const ext=file.name.split('.').pop()?.toLowerCase()||'bin';const postId=crypto.randomUUID();const path=user.id+'/'+postId+'/media.'+ext;const upload=await supabase.storage.from('post-media').upload(path,file,{contentType:file.type,upsert:false});if(upload.error){setBusy(false);return alert(upload.error.message)}if(cancelRef.current){await supabase.storage.from('post-media').remove([path]);setBusy(false);return}const post=await supabase.from('posts').insert({id:postId,user_id:user.id,caption:caption.trim(),visibility});if(post.error){await supabase.storage.from('post-media').remove([path]);setBusy(false);return alert(post.error.message)}if(cancelRef.current){await supabase.from('posts').delete().eq('id',postId).eq('user_id',user.id);await supabase.storage.from('post-media').remove([path]);setBusy(false);return}const media=await supabase.from('media').insert({post_id:postId,storage_path:path,media_type:file.type.startsWith('video/')?'video':'image',mime_type:file.type});if(media.error){await supabase.from('posts').delete().eq('id',postId).eq('user_id',user.id);await supabase.storage.from('post-media').remove([path]);setBusy(false);return alert(media.error.message)}if(cancelRef.current){await supabase.from('media').delete().eq('post_id',postId);await supabase.from('posts').delete().eq('id',postId).eq('user_id',user.id);await supabase.storage.from('post-media').remove([path]);setBusy(false);return}setBusy(false);router.push('/');router.refresh()}
 return <section className="card form-card"><h2>Create</h2><p className="muted">Share a photo or video with Mirror Gram.</p><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}><button type="button" className="primary" onClick={()=>cameraRef.current?.click()}>📷 Camera</button><button type="button" className="secondary" onClick={()=>uploadRef.current?.click()}>⬆️ Upload</button><button type="button" className="secondary" onClick={openLive}>🔴 Live</button></div><input ref={cameraRef} type="file" accept="image/*,video/*" capture="environment" onChange={e=>choose(e.target.files?.[0])} style={{position:'absolute',width:1,height:1,opacity:.01,pointerEvents:'none'}}/><input ref={uploadRef} type="file" accept="image/*,video/*" onChange={e=>choose(e.target.files?.[0])} style={{position:'absolute',width:1,height:1,opacity:.01,pointerEvents:'none'}}/>{live&&<div style={{padding:12,borderRadius:10,background:'#eef7ff',border:'1px solid #9ec9f8',color:'#0b4c9c'}}><strong>🔴 Live camera</strong><video ref={liveVideoRef} autoPlay muted playsInline style={{display:'block',width:'100%',marginTop:10,borderRadius:12,background:'#071b41',maxHeight:420,objectFit:'cover'}}/>{liveBusy&&<div style={{marginTop:8}}>Opening camera…</div>}{liveError&&<div style={{marginTop:8,color:'#991b1b'}}>{liveError}</div>}<div style={{marginTop:8,fontSize:13}}>Camera preview is active on this device. Viewer broadcasting still needs a streaming provider.</div><button type="button" className="secondary" style={{marginTop:10}} onClick={closeLive}>Close camera</button></div>}<label className="dropzone">{preview?(file?.type.startsWith('video/')?<video src={preview} controls/>:<img src={preview} alt="Preview"/>):<span>Choose photo or video</span>}</label><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={2200} placeholder="Write a caption…"/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">Public</option><option value="followers">Followers</option><option value="private">Only me</option></select><div style={{display:'flex',gap:10}}><button className="primary" onClick={publish} disabled={busy}>{busy?'Uploading…':'Publish'}</button>{busy&&<button type="button" className="secondary" onClick={cancelUpload}>Cancel upload</button>}</div>{cancelled&&!busy&&<div className="muted" style={{marginTop:8}}>Upload cancelled. No post was created.</div>}</section>
}