'use client'
import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

export default function CreatePostForm(){
 const supabase=createClient(); const router=useRouter(); const uploadRef=useRef<HTMLInputElement>(null); const cameraRef=useRef<HTMLInputElement>(null); const liveVideoRef=useRef<HTMLVideoElement>(null); const liveStreamRef=useRef<MediaStream|null>(null); const cancelRef=useRef(false)
 const [files,setFiles]=useState<File[]>([]); const [live,setLive]=useState(false); const [liveError,setLiveError]=useState(''); const [liveBusy,setLiveBusy]=useState(false); const [caption,setCaption]=useState(''); const [visibility,setVisibility]=useState('public'); const [busy,setBusy]=useState(false); const [cancelled,setCancelled]=useState(false); const [preview,setPreview]=useState<string|null>(null)
 useEffect(()=>()=>{liveStreamRef.current?.getTracks().forEach(t=>t.stop())},[])
 function chooseMany(list:FileList|null){const chosen=Array.from(list??[]);if(!chosen.length)return;for(const f of chosen){if(!['image/','video/'].some(p=>f.type.startsWith(p)))return alert('Choose images or videos only.');if(f.size>50*1024*1024)return alert('Each file must be 50 MB or smaller.')}cancelRef.current=false;setCancelled(false);setFiles(chosen);setPreview(URL.createObjectURL(chosen[0]))}
 async function openLive(){setLive(true);setLiveError('');setLiveBusy(true);try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('This browser does not provide camera access.');const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});liveStreamRef.current=stream;if(liveVideoRef.current){liveVideoRef.current.srcObject=stream;await liveVideoRef.current.play().catch(()=>{})}const {data:{user}}=await supabase.auth.getUser();if(user)await supabase.from('live_streams').insert({host_user_id:user.id,title:'Mirror Gram Live',category:'creator',status:'live',started_at:new Date().toISOString()})}catch(e){setLiveError(e instanceof Error?e.message:'Camera access was denied. Check your browser camera/microphone permission.')}finally{setLiveBusy(false)}}
 function closeLive(){liveStreamRef.current?.getTracks().forEach(t=>t.stop());liveStreamRef.current=null;setLive(false)}
 function cancelUpload(){if(!busy)return;cancelRef.current=true;setCancelled(true);setBusy(false)}
 async function publish(){if(!files.length)return alert('Choose at least one photo or video first.');if(busy)return;cancelRef.current=false;setCancelled(false);setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return router.push('/login')}const postId=crypto.randomUUID();const uploaded:string[]=[];try{for(let i=0;i<files.length;i++){if(cancelRef.current)throw new Error('UPLOAD_CANCELLED');const f=files[i];const ext=f.name.split('.').pop()?.toLowerCase()||'bin';const path=user.id+'/'+postId+'/media-'+i+'.'+ext;const upload=await supabase.storage.from('post-media').upload(path,f,{contentType:f.type,upsert:false});if(upload.error)throw upload.error;uploaded.push(path)}if(cancelRef.current)throw new Error('UPLOAD_CANCELLED');const post=await supabase.from('posts').insert({id:postId,user_id:user.id,caption:caption.trim(),visibility});if(post.error)throw post.error;const mediaRows=files.map((f,i)=>({post_id:postId,storage_path:uploaded[i],media_type:f.type.startsWith('video/')?'video':'image',mime_type:f.type}));const media=await supabase.from('media').insert(mediaRows);if(media.error)throw media.error;if(cancelRef.current)throw new Error('UPLOAD_CANCELLED');setBusy(false);router.push('/');router.refresh()}catch(e){if(e instanceof Error&&e.message==='UPLOAD_CANCELLED'){await supabase.from('media').delete().eq('post_id',postId);await supabase.from('posts').delete().eq('id',postId).eq('user_id',user.id)}else{await supabase.from('media').delete().eq('post_id',postId);await supabase.from('posts').delete().eq('id',postId).eq('user_id',user.id);if(uploaded.length)await supabase.storage.from('post-media').remove(uploaded);alert(e instanceof Error?e.message:'Post could not be published.')}if(uploaded.length)await supabase.storage.from('post-media').remove(uploaded);setBusy(false)}}}