'use client'
import { useEffect,useState } from 'react'
import { createClient } from '@/lib/supabase/client'
type C={id:string};type M={id:string;conversation_id:string;sender_id:string;body:string;created_at:string};type Friend={id:string;username:string;display_name:string;avatar:string|null;online:boolean}
export default function MessagesClient({userId,initialUsername=''}:{userId:string;initialUsername?:string}){const s=createClient();const[cs,setCs]=useState<C[]>([]),[active,setActive]=useState<string|null>(null),[ms,setMs]=useState<M[]>([]),[body,setBody]=useState(''),[other,setOther]=useState(initialUsername),[friends,setFriends]=useState<Friend[]>([]),[sending,setSending]=useState(false),[messageError,setMessageError]=useState('')
 async function loadFriends(){const {data:rows}=await s.from('follows').select('following_id,profiles!follows_following_id_fkey(id,username,display_name,avatar_path,last_seen_at)').eq('follower_id',userId).limit(20);const now=Date.now();const next=(rows??[]).map((r:any)=>{const p=r.profiles;const last=p?.last_seen_at?Date.parse(p.last_seen_at):0;return{id:p?.id,username:p?.username??'user',display_name:p?.display_name??'',avatar:null,online:last>now-5*60*1000}}).filter(x=>x.id);setFriends(next)}
 useEffect(()=>{load();loadFriends();const t=setInterval(loadFriends,30000);return()=>clearInterval(t)},[])
 useEffect(()=>{if(!active)return;loadMessages(active);const ch=s.channel(`messages:${active}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${active}`},payload=>setMs(v=>v.some(x=>x.id===payload.new.id)?v:[...v,payload.new as M])).subscribe();return()=>{s.removeChannel(ch)}},[active])
 async function load(){const{data}=await s.from('conversation_members').select('conversation_id').eq('user_id',userId);const list=(data??[]).map(x=>({id:x.conversation_id}));setCs(list);if(list[0])setActive(list[0].id)}async function loadMessages(id:string){const{data}=await s.from('messages').select('*').eq('conversation_id',id).order('created_at',{ascending:true});setMs(data??[])}async function start(){const name=other.trim().toLowerCase();if(!name)return;const{data:p}=await s.from('profiles').select('id').eq('username',name).single();if(!p)return alert('User not found');if(p.id===userId)return alert('Choose another user.');const{data:c,error}=await s.from('conversations').insert({}).select('id').single();if(error||!c)return alert(error?.message??'Could not create conversation');const self=await s.from('conversation_members').insert({conversation_id:c.id,user_id:userId});if(self.error)return alert(self.error.message);const ins=await s.from('conversation_members').insert({conversation_id:c.id,user_id:p.id});if(ins.error)return alert(ins.error.message);setCs(v=>[...v,{id:c.id}]);setActive(c.id);setOther('')}async function send(){const text=body.trim();if(!active||!text||sending)return;setSending(true);setMessageError('');const{data:{user}}=await s.auth.getUser();if(!user){setMessageError('Please log in again.');setSending(false);return}const{data,error}=await s.from('messages').insert({conversation_id:active,sender_id:user.id,body:text}).select('id,conversation_id,sender_id,body,created_at').single();if(error){setMessageError(error.message)}else{setMs(v=>v.some(x=>x.id===data.id)?v:[...v,data as M]);setBody('')}setSending(false)}
 return <><section className="online-bar card"><div className="online-title"><strong>Active friends</strong><span>People you follow who were recently active</span></div><div className="online-friends">{friends.length?friends.map(f=><button className="online-friend" key={f.id} onClick={()=>setOther(f.username)}><span className={f.online?'online-dot':'offline-dot'}></span><div><b>@{f.username}</b><small>{f.online?'Online now':'Recently active'}</small></div></button>):<span className="muted">Follow people to see them here.</span>}</div></section><div className="messages-grid"><section className="card"><h3>Start a chat</h3><div className="inline"><input value={other} onChange={e=>setOther(e.target.value)} placeholder="Username"/><button onClick={start}>Start</button></div><h3>Conversations</h3>{cs.map(c=><button className={active===c.id?'conversation active':'conversation'} key={c.id} onClick={()=>setActive(c.id)}>Conversation · {c.id.slice(0,8)}</button>)}</section><section className="card chat"><div className="chat-scroll">{ms.map(m=><div className={m.sender_id===userId?'bubble mine':'bubble'} key={m.id}>{m.body}</div>)}</div><div className="inline"><input value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Write a message…" maxLength={5000}/><button onClick={send} disabled={!active||!body.trim()||sending}>{sending?'Sending…':'Send'}</button></div>{messageError&&<div className="message-error">{messageError}</div>}</section></div></>}
