'use client'
import Link from 'next/link'
import { useEffect, useMemo, useRef, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import FollowButton from './FollowButton'

type Post = { id:string; user_id:string; caption:string; created_at:string; username:string; display_name:string; mediaUrl?:string|null; mediaType?:string|null; mediaPath?:string|null; likeCount:number; commentCount:number; liked:boolean; saved:boolean }

export default function PostCard({ post, canInteract = true }: { post:Post; canInteract?:boolean }) {
  const supabase=useMemo(()=>createClient(),[])
  const replaceRef=useRef<HTMLInputElement>(null)
  const [liked,setLiked]=useState(post.liked),[reaction,setReaction]=useState<string|null>(post.liked?'like':null),[showReactions,setShowReactions]=useState(false),[saved,setSaved]=useState(post.saved),[likes,setLikes]=useState(post.likeCount),[comment,setComment]=useState(''),[comments,setComments]=useState(post.commentCount),[busy,setBusy]=useState(false),[currentUserId,setCurrentUserId]=useState<string|null>(null),[editing,setEditing]=useState(false),[caption,setCaption]=useState(post.caption),[deleteBusy,setDeleteBusy]=useState(false),[replaceBusy,setReplaceBusy]=useState(false)

  useEffect(()=>{supabase.auth.getUser().then(({data:{user}})=>setCurrentUserId(user?.id??null))},[supabase])
  const isOwner=currentUserId===post.user_id

  async function toggleLike(){if(!canInteract||busy)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return};if(liked){const {error}=await supabase.from('likes').delete().eq('post_id',post.id).eq('user_id',user.id);if(!error){setLiked(false);setLikes(v=>Math.max(0,v-1))}}else{const {error}=await supabase.from('likes').insert({post_id:post.id,user_id:user.id});if(!error){setLiked(true);setLikes(v=>v+1)}}setBusy(false)}
  const reactions=[['like','👍'],['love','❤️'],['haha','😂'],['wow','😮'],['sad','😢'],['angry','😡'],['celebrate','🎉'],['support','💙']] as const
  async function chooseReaction(kind:string){if(!canInteract)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const previous=reaction;if(previous===kind){const {error}=await (supabase as any).from('post_reactions').delete().eq('post_id',post.id).eq('user_id',user.id);if(!error){setReaction(null);setLiked(false);setLikes(v=>Math.max(0,v-1))}}else{const {error}=await (supabase as any).from('post_reactions').upsert({post_id:post.id,user_id:user.id,reaction:kind},{onConflict:'post_id,user_id'});if(!error){setReaction(kind);setLiked(kind==='like');if(!previous)setLikes(v=>v+1)}}setShowReactions(false)}
  async function toggleSave(){if(!canInteract||busy)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){setBusy(false);return};if(saved){const {error}=await supabase.from('saved_posts').delete().eq('post_id',post.id).eq('user_id',user.id);if(!error)setSaved(false)}else{const {error}=await supabase.from('saved_posts').insert({post_id:post.id,user_id:user.id});if(!error)setSaved(true)}setBusy(false)}
  async function addComment(){const body=comment.trim();if(!canInteract||!body||busy)return;setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(user){const {error}=await supabase.from('comments').insert({post_id:post.id,user_id:user.id,body});if(!error){setComment('');setComments(v=>v+1)}}setBusy(false)}
  async function reportPost(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const reason=window.prompt('Reason: spam, harassment, unsafe, privacy, impersonation, copyright, or other');if(!reason)return;await supabase.from('reports').insert({reporter_id:user.id,post_id:post.id,reported_user_id:post.user_id,reason});window.alert('Thanks. Your report was submitted.')}

  async function saveCaption(){const next=caption.trim();if(!isOwner||next.length>2200)return;setBusy(true);const {error}=await supabase.from('posts').update({caption:next}).eq('id',post.id).eq('user_id',post.user_id);if(error)window.alert(error.message);else{setCaption(next);setEditing(false)}setBusy(false)}
  async function deletePost(){if(!isOwner||deleteBusy)return;if(!window.confirm('Delete this post permanently?'))return;setDeleteBusy(true);const {data:media}=await supabase.from('media').select('storage_path').eq('post_id',post.id);const {error:mediaError}=await supabase.from('media').delete().eq('post_id',post.id);if(mediaError){window.alert(mediaError.message);setDeleteBusy(false);return}const {error:postError}=await supabase.from('posts').delete().eq('id',post.id).eq('user_id',post.user_id);if(postError){window.alert(postError.message);setDeleteBusy(false);return}if(media?.length)await supabase.storage.from('post-media').remove(media.map(m=>m.storage_path));window.location.reload()}
  async function replaceMedia(file?:File){if(!isOwner||!file)return;if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))return window.alert('Choose an image or video.');if(file.size>50*1024*1024)return window.alert('Maximum file size is 50 MB.');setReplaceBusy(true);const {data:old}=await supabase.from('media').select('id,storage_path').eq('post_id',post.id).limit(1).maybeSingle();const ext=file.name.split('.').pop()?.toLowerCase()||'bin';const path=`${post.user_id}/${post.id}/media-${Date.now()}.${ext}`;const upload=await supabase.storage.from('post-media').upload(path,file,{contentType:file.type,upsert:false});if(upload.error){window.alert(upload.error.message);setReplaceBusy(false);return}const mediaType=file.type.startsWith('video/')?'video':'image';let result;if(old)result=await supabase.from('media').update({storage_path:path,media_type:mediaType,mime_type:file.type}).eq('id',old.id).eq('post_id',post.id);else result=await supabase.from('media').insert({post_id:post.id,storage_path:path,media_type:mediaType,mime_type:file.type});if(result.error){await supabase.storage.from('post-media').remove([path]);window.alert(result.error.message);setReplaceBusy(false);return}if(old?.storage_path)await supabase.storage.from('post-media').remove([old.storage_path]);window.location.reload()}

  return <article className="card post">
    <div className="post-head"><div className="post-author"><Link href={isOwner?'/profile':'/profile/'+post.user_id} className="post-author-link"><strong>@{post.username}</strong><span>{post.display_name}</span></Link>{currentUserId&&currentUserId!==post.user_id&&canInteract&&<FollowButton targetId={post.user_id}/>}</div>
      <div style={{display:'flex',gap:8,alignItems:'center'}}>{isOwner&&<details><summary className="ghost" style={{cursor:'pointer',listStyle:'none'}}>•••</summary><div style={{position:'absolute',zIndex:5,background:'#fff',border:'1px solid #dbe5f0',borderRadius:12,padding:8,boxShadow:'0 8px 24px rgba(0,0,0,.12)',display:'grid',gap:6}}><button className="ghost" onClick={()=>setEditing(true)}>✏️ Edit caption</button><button className="ghost" onClick={()=>replaceRef.current?.click()} disabled={replaceBusy}>{replaceBusy?'Replacing…':'🖼️ Replace media'}</button><button className="ghost" onClick={deletePost} disabled={deleteBusy}>{deleteBusy?'Deleting…':'🗑️ Delete post'}</button></div></details>}<button className="ghost" onClick={reportPost}>Report</button></div>
    </div>
    {editing?<div style={{display:'grid',gap:8,margin:'10px 0'}}><textarea value={caption} onChange={e=>setCaption(e.target.value)} maxLength={2200} autoFocus/><div style={{display:'flex',gap:8}}><button className="primary" onClick={saveCaption} disabled={busy}>{busy?'Saving…':'Save caption'}</button><button className="secondary" onClick={()=>{setCaption(post.caption);setEditing(false)}}>Cancel</button></div></div>:post.caption&&<p className="post-caption">{caption}</p>}
    <input ref={replaceRef} type="file" accept="image/*,video/*" onChange={e=>replaceMedia(e.target.files?.[0])} style={{display:'none'}}/>
    {post.mediaUrl&&(post.mediaType==='video'?<video className="post-media" controls playsInline src={post.mediaUrl}/>:<img className="post-media" src={post.mediaUrl} alt="Post media"/>)}
    <div className="post-body"><div className="actions"><div className="reaction-wrap"><button onClick={()=>setShowReactions(v=>!v)} disabled={!canInteract}>{reaction?reactions.find(x=>x[0]===reaction)?.[1]:'👍'} {likes}</button>{showReactions&&<div className="reaction-picker">{reactions.map(r=><button key={r[0]} title={r[0]} onClick={()=>chooseReaction(r[0])}>{r[1]}</button>)}</div>}</div><button onClick={toggleLike} disabled={!canInteract}>{liked?'♥':'♡'} {likes}</button><button disabled>{comments} comments</button><button onClick={toggleSave} disabled={!canInteract}>{saved?'Saved':'Save'}</button></div><div className="comment-box"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a kind comment…" maxLength={1000}/><button onClick={addComment} disabled={!canInteract||!comment.trim()}>Post</button></div></div>
  </article>
}
