
'use client'
import { useEffect, useRef, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Story = { id:string; user_id:string; username:string; display_name:string; mediaUrl:string; mediaType:'image'|'video'; likeCount:number; liked:boolean; commentCount:number }
type StoryRow = { id:string; user_id:string; storage_path:string; media_type:'image'|'video'; created_at:string; profiles:{username:string|null;display_name:string|null}|null }

export default function StoryBar({initialStories}:{initialStories:Story[]}){
 const s=createClient(), inputRef=useRef<HTMLInputElement>(null)
 const [stories,setStories]=useState<Story[]>(initialStories),[busy,setBusy]=useState(false),[viewer,setViewer]=useState<Story|null>(null),[error,setError]=useState(''),[comment,setComment]=useState(''),[postingComment,setPostingComment]=useState(false)
 async function loadStories(){
  const {data:{user}}=await s.auth.getUser(); if(!user)return
  const q=(s as any).from('stories').select('id,user_id,storage_path,media_type,created_at,profiles!stories_user_id_fkey(username,display_name)').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(30)
  const {data,error}=await q;if(error)return
  const byUser=new Map<string,StoryRow>();for(const row of (data??[]) as StoryRow[])if(!byUser.has(row.user_id))byUser.set(row.user_id,row)
  const rows=await Promise.all([...byUser.values()].map(async row=>{const signed=await s.storage.from('stories').createSignedUrl(row.storage_path,86400);if(!signed.data?.signedUrl)return null;const [{data:likes},{count:commentCount}]=await Promise.all([(s as any).from('story_likes').select('user_id').eq('story_id',row.id),(s as any).from('story_comments').select('*',{count:'exact',head:true}).eq('story_id',row.id)]);return {id:row.id,user_id:row.user_id,username:row.user_id===user.id?'you':(row.profiles?.username??'user'),display_name:row.user_id===user.id?'Your Story':(row.profiles?.display_name??''),mediaUrl:signed.data.signedUrl,mediaType:row.media_type,likeCount:likes?.length??0,liked:(likes??[]).some((x:{user_id:string})=>x.user_id===user.id),commentCount:commentCount??0} as Story}))
  setStories(rows.filter((x):x is Story=>!!x))
 }
 useEffect(()=>{loadStories()},[])
 async function addStory(file?:File){if(!file)return;if(!file.type.startsWith('image/')&&!file.type.startsWith('video/')){setError('Choose a photo or video for your story.');return}if(file.size>50*1024*1024){setError('Story files must be 50 MB or smaller.');return}setBusy(true);setError('');try{const {data:{user}}=await s.auth.getUser();if(!user)throw new Error('Please log in again before posting a story.');const id=crypto.randomUUID(),ext=file.name.split('.').pop()?.toLowerCase()||'bin',path=`${user.id}/${id}/story.${ext}`;const upload=await s.storage.from('stories').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const inserted=await (s as any).from('stories').insert({id,user_id:user.id,storage_path:path,media_type:file.type.startsWith('video/')?'video':'image',caption:''}).select('id').single();if(inserted.error){await s.storage.from('stories').remove([path]);throw inserted.error}await loadStories()}catch(e){setError(e instanceof Error?e.message:'Story could not be published.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
 async function toggleLike(){if(!viewer)return;const {data:{user}}=await s.auth.getUser();if(!user)return;if(viewer.liked){const {error}=await (s as any).from('story_likes').delete().eq('story_id',viewer.id).eq('user_id',user.id);if(error)return;setViewer(v=>v?{...v,liked:false,likeCount:Math.max(0,v.likeCount-1)}:v);setStories(v=>v.map(x=>x.id===viewer.id?{...x,liked:false,likeCount:Math.max(0,x.likeCount-1)}:x))}else{const {error}=await (s as any).from('story_likes').insert({story_id:viewer.id,user_id:user.id});if(error)return;setViewer(v=>v?{...v,liked:true,likeCount:v.likeCount+1}:v);setStories(v=>v.map(x=>x.id===viewer.id?{...x,liked:true,likeCount:x.likeCount+1}:x))}}
 async function addComment(){const body=comment.trim();if(!viewer||!body||postingComment)return;setPostingComment(true);const {data:{user}}=await s.auth.getUser();if(user){const {error}=await s.from('story_comments').insert({story_id:viewer.id,user_id:user.id,body});if(!error){setComment('');setViewer(v=>v?{...v,commentCount:v.commentCount+1}:v)}}setPostingComment(false)}
 return <>
  <div className="card stories" aria-label="Stories"><button type="button" className="story story-button" onClick={()=>inputRef.current?.click()} disabled={busy}><div className="story-avatar"><div>+</div></div><b>{busy?'Posting…':'Your Story'}</b></button>{stories.map(story=><button type="button" className="story story-button" key={story.id} onClick={()=>{setViewer(story);setComment('')}}><div className="story-avatar"><div>{story.username.slice(0,2).toUpperCase()}</div></div><span>@{story.username}</span><small>{story.likeCount} ♥ · {story.commentCount} 💬</small></button>)}{!stories.length&&<span className="muted story-empty">No active stories yet.</span>}</div>
  <input ref={inputRef} type="file" accept="image/*,video/*" onChange={e=>addStory(e.target.files?.[0])} style={{display:'none'}}/>
  {error&&<div className="story-error">{error}<button type="button" onClick={()=>setError('')}>Close</button></div>}
  {viewer&&<div className="story-viewer" role="dialog" aria-modal="true" onClick={()=>setViewer(null)}><div className="story-viewer-card normal-story-viewer" onClick={e=>e.stopPropagation()}><button type="button" className="story-close" onClick={()=>setViewer(null)}>×</button><div className="story-viewer-head"><div className="story-viewer-avatar">{viewer.username.slice(0,2).toUpperCase()}</div><div><strong>@{viewer.username}</strong><span>{viewer.display_name}</span></div></div>{viewer.mediaType==='video'?<video src={viewer.mediaUrl} controls autoPlay playsInline/>:<img src={viewer.mediaUrl} alt="Story" />}<div className="story-actions"><button onClick={toggleLike}>{viewer.liked?'♥ Liked':'♡ Like'} {viewer.likeCount}</button><span>{viewer.commentCount} comments</span></div><div className="comment-box"><input value={comment} onChange={e=>setComment(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addComment()}} placeholder="Comment on this story…" maxLength={1000}/><button onClick={addComment} disabled={!comment.trim()||postingComment}>Post</button></div></div></div>}
 </>
}
