'use client'
import { useEffect, useRef, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'

type Stream={id:string;title:string;category:string;created_at:string;profiles:{username:string|null;display_name:string|null}|null}

export default function LivePage(){
 const s=createClient(), videoRef=useRef<HTMLVideoElement>(null), viewerRef=useRef<HTMLVideoElement>(null), pcs=useRef<Record<string,RTCPeerConnection>>({})
 const [streams,setStreams]=useState<Stream[]>([]),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[liveId,setLiveId]=useState<string|null>(null),[watchId,setWatchId]=useState<string|null>(null),[error,setError]=useState('')
 useEffect(()=>{load();const ch=s.channel('live-streams').on('postgres_changes',{event:'*',schema:'public',table:'live_streams'},load).subscribe();return()=>{s.removeChannel(ch)}},[])
 async function load(){const {data}=await s.from('live_streams').select('id,title,category,created_at,profiles(username,display_name)').eq('status','live').order('created_at',{ascending:false});setStreams((data??[]) as Stream[])}
 function closePeers(){Object.values(pcs.current).forEach(p=>p.close());pcs.current={}}
 async function start(){setError('');if(!title.trim())return;setBusy(true);try{const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}const media=await navigator.mediaDevices.getUserMedia({video:true,audio:true});if(videoRef.current){videoRef.current.srcObject=media;await videoRef.current.play()}const {data,error}=await s.from('live_streams').insert({host_user_id:user.id,title:title.trim(),category:'creator',status:'live',started_at:new Date().toISOString()}).select('id').single();if(error)throw error;setLiveId(data.id);const ch=s.channel('live:'+data.id);ch.on('broadcast',{event:'viewer-join'},async({payload})=>{const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pcs.current[payload.viewerId]=pc;media.getTracks().forEach(t=>pc.addTrack(t,media));pc.onicecandidate=e=>{if(e.candidate)ch.send({type:'broadcast',event:'host-ice',payload:{viewerId:payload.viewerId,candidate:e.candidate}})};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await ch.send({type:'broadcast',event:'offer',payload:{viewerId:payload.viewerId,sdp:offer}})}).on('broadcast',{event:'answer'},async({payload})=>{const pc=pcs.current[payload.viewerId];if(pc&&payload.sdp)await pc.setRemoteDescription(payload.sdp)}).on('broadcast',{event:'viewer-ice'},async({payload})=>{const pc=pcs.current[payload.viewerId];if(pc&&payload.candidate)await pc.addIceCandidate(payload.candidate)}).subscribe();setTimeout(()=>ch.send({type:'broadcast',event:'host-ready',payload:{}}),500)}catch(e){setError(e instanceof Error?e.message:'Camera or microphone access failed.');setLiveId(null)}finally{setBusy(false)}}
 async function watch(id:string){setError('');closePeers();setWatchId(id);const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pcs.current.viewer=pc;pc.ontrack=e=>{if(viewerRef.current)viewerRef.current.srcObject=e.streams[0]};const ch=s.channel('live:'+id);ch.on('broadcast',{event:'offer'},async({payload})=>{if(payload.viewerId!==user.id)return;await pc.setRemoteDescription(payload.sdp);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await ch.send({type:'broadcast',event:'answer',payload:{viewerId:user.id,sdp:answer}})}).on('broadcast',{event:'host-ice'},async({payload})=>{if(payload.viewerId===user.id&&payload.candidate)await pc.addIceCandidate(payload.candidate)}).subscribe(status=>{if(status==='SUBSCRIBED')ch.send({type:'broadcast',event:'viewer-join',payload:{viewerId:user.id}})})}
 async function end(){if(!liveId)return;const {error}=await s.from('live_streams').update({status:'ended',ended_at:new Date().toISOString()}).eq('id',liveId);if(error)setError(error.message);const media=videoRef.current?.srcObject as MediaStream|null;media?.getTracks().forEach(t=>t.stop());closePeers();setLiveId(null);load()}
 return <main className="shell"><header className="topbar"><div><h1>Mirror Gram Live</h1><p>Broadcast from your camera and connect with viewers.</p></div><Link href="/">Home</Link></header>
 {error&&<div className="error">{error}</div>}
 {!liveId?<section className="card form-card"><h2>Start a live session</h2><p className="muted">Allow camera and microphone access to start. Viewers receive your live video through a direct WebRTC connection.</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Live title" maxLength={150}/><button className="primary" disabled={busy} onClick={start}>{busy?'Starting…':'Go Live'}</button></section>:<section className="card live-stage"><div className="badge">LIVE</div><video ref={videoRef} autoPlay muted playsInline/><div className="inline"><strong>{title}</strong><button onClick={end}>End live</button></div></section>}
 {watchId&&<section className="card live-stage"><div className="badge">WATCHING LIVE</div><video ref={viewerRef} autoPlay playsInline controls/><button onClick={()=>{closePeers();setWatchId(null)}}>Stop watching</button></section>}
 <section className="list"><h2>Live now</h2>{streams.filter(x=>x.id!==liveId).map(x=><article className="card" key={x.id}><span className="badge">LIVE</span><h3>{x.title}</h3><p>@{x.profiles?.username??'creator'} · {x.category}</p><button className="primary" onClick={()=>watch(x.id)}>Watch live</button></article>)}{!streams.length&&<p className="muted">No one is live right now.</p>}</section></main>
}