'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
export default function LivePage(){const s=createClient();const [streams,setStreams]=useState<any[]>([]);const [title,setTitle]=useState('');const [busy,setBusy]=useState(false)
useEffect(()=>{load();const ch=s.channel('live-streams').on('postgres_changes',{event:'*',schema:'public',table:'live_streams'},()=>load()).subscribe();return()=>{s.removeChannel(ch)}},[])
async function load(){const {data}=await s.from('live_streams').select('id,title,category,status,created_at,profiles(username,display_name)').eq('status','live').order('created_at',{ascending:false});setStreams(data??[])}
async function start(){if(!title.trim())return;setBusy(true);const {data:{user}}=await s.auth.getUser();if(!user){location.href='/login';return}const {error}=await s.from('live_streams').insert({host_user_id:user.id,title:title.trim(),category:'creator',status:'live',started_at:new Date().toISOString()});if(error)alert(error.message);else setTitle('');setBusy(false);load()}
return <main className="shell"><header className="topbar"><div><h1>Mirror Gram Live</h1><p>Live infrastructure foundation with moderation-first controls.</p></div><Link href="/">Home</Link></header><section className="card form-card"><h2>Start a live session</h2><p className="muted">This creates the moderated stream record. A production video provider/ingest endpoint still needs to be connected before real camera broadcasting.</p><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Live title" maxLength={150}/><button className="primary" disabled={busy} onClick={start}>{busy?'Starting…':'Create live session'}</button></section><section className="list">{streams.map(x=><article className="card" key={x.id}><span className="badge">LIVE</span><h3>{x.title}</h3><p>@{x.profiles?.username??'creator'} · {x.category}</p></article>)}</section></main>}
